---
- name: Upgrade installed Ubuntu packages
  hosts: ubuntuvagrant
  become: True
  tasks:

    - name: Install Aptitude
      apt:
        name: aptitude
        update_cache: yes

    - name: apt-get upgrade
      apt:
        name: "*"
        state: latest
